# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class addEditCoffee(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(245, 337)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.volumeInput = QtWidgets.QLineEdit(Form)
        self.volumeInput.setObjectName("volumeInput")
        self.gridLayout.addWidget(self.volumeInput, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.descriptionInput = QtWidgets.QLineEdit(Form)
        self.descriptionInput.setObjectName("descriptionInput")
        self.gridLayout.addWidget(self.descriptionInput, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.nameInput = QtWidgets.QLineEdit(Form)
        self.nameInput.setObjectName("nameInput")
        self.gridLayout.addWidget(self.nameInput, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.priceInput = QtWidgets.QLineEdit(Form)
        self.priceInput.setObjectName("priceInput")
        self.gridLayout.addWidget(self.priceInput, 4, 1, 1, 1)
        self.groundInput = QtWidgets.QLineEdit(Form)
        self.groundInput.setObjectName("groundInput")
        self.gridLayout.addWidget(self.groundInput, 2, 1, 1, 1)
        self.roastingInput = QtWidgets.QLineEdit(Form)
        self.roastingInput.setObjectName("roastingInput")
        self.gridLayout.addWidget(self.roastingInput, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.addButton = QtWidgets.QPushButton(Form)
        self.addButton.setObjectName("addButton")
        self.verticalLayout.addWidget(self.addButton)
        self.statusBar = QtWidgets.QLabel(Form)
        self.statusBar.setText("")
        self.statusBar.setObjectName("statusBar")
        self.verticalLayout.addWidget(self.statusBar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Price:"))
        self.label.setText(_translate("Form", "Name:"))
        self.label_4.setText(_translate("Form", "Description:"))
        self.label_2.setText(_translate("Form", "Roasting:"))
        self.label_6.setText(_translate("Form", "Volume:"))
        self.label_3.setText(_translate("Form", "Ground:"))
        self.addButton.setText(_translate("Form", "Добавить"))
